version: '3'

services:
    app:
        container_name: python-msg
        build: .
        volumes:
            - ./:/usr/app/src
        ports:
            - 8000:5000
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq-py
        hostname: "rabbitmq"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "user"
            RABBITMQ_DEFAULT_PASS: "password"
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "path/to/data"
            - "path/to/log"
volumes:
    data: {}
    logs: {}